@startuml
scale 2

class cFrameObj {
	+AddByCoord()
	+AddByPoint()
	+ChangeName()
	+Count()
	+Delete()
	+DeleteLateralBracing()
	+DeleteLoadDistributed()
	+DeleteLoadPoint()
	+DeleteLoadTemperature()
	+DeleteMass()
	+DeleteModifiers()
	+DeleteSpring()
	+GetAllFrames()
	+GetColumnSpliceOverwrite()
	+GetCurved_2()
	+GetDesignOrientation()
	+GetDesignProcedure()
	+GetElm()
	+GetEndLengthOffset()
	+GetGroupAssign()
	+GetGUID()
	+GetHingeAssigns()
	+GetInsertionPoint()
	+GetLabelFromName()
	+GetLabelNameList()
	+GetLateralBracing()
	+GetLoadDistributed()
	+GetLoadPoint()
	+GetLoadTemperature()
	+GetLocalAxes()
	+GetMass()
	+GetMaterialOverwrite()
	+GetModifiers()
	+GetNameFromLabel()
	+GetNameList()
	+GetNameListOnStory()
	+GetOutputStations()
	+GetPier()
	+GetPoints()
	+GetReleases()
	+GetSection()
	+GetSectionNonPrismatic()
	+GetSelected()
	+GetSpandrel()
	+GetSpringAssignment()
	+GetSupports()
	+GetTCLimits()
	+GetTransformationMatrix()
	+GetTypeOAPI()
	+SetColumnSpliceOverwrite()
	+SetDesignProcedure()
	+SetEndLengthOffset()
	+SetGroupAssign()
	+SetGUID()
	+SetInsertionPoint()
	+SetLateralBracing()
	+SetLoadDistributed()
	+SetLoadPoint()
	+SetLoadTemperature()
	+SetLocalAxes()
	+SetMass()
	+SetMaterialOverwrite()
	+SetModifiers()
	+SetOutputStations()
	+SetPier()
	+SetReleases()
	+SetSection()
	+SetSelected()
	+SetSpandrel()
	+SetSpringAssignment()
	+SetTCLimits()
}

@enduml