@startuml
scale 2

class cLoadPatterns {
	+AutoSeismic
	+AutoWind
	+Add()
	+ChangeName()
	+Count()
	+Delete()
	+GetAutoSeismicCode()
	+GetAutoWindCode()
	+GetLoadType()
	+GetNameList()
	+GetSelfWTMultiplier()
	+SetLoadType()
	+SetSelfWTMultiplier()
}

@enduml