@startuml
scale 2

class cPointObj {
	+ AddCartesian()
	+ ChangeName()
	+ Count()
	+ CountLoadDispl()
	+ CountLoadForce()
	+ CountPanelZone()
	+ CountRestraint()
	+ CountSpring()
	+ DeleteLoadDispl()
	+ DeleteLoadForce()
	+ DeleteMass()
	+ DeletePanelZone()
	+ DeleteRestraint()
	+ DeleteSpecialPoint()
	+ DeleteSpring()
	+ GetAllPoints()
	+ GetCommonTo()
	+ GetConnectivity()
	+ GetCoordCartesian()
	+ GetCoordCylindrical()
	+ GetCoordSpherical()
	+ GetDiaphragm()
	+ GetElm()
	+ GetGroupAssign()
	+ GetGUID()
	+ GetLabelFromName()
	+ GetLabelNameList()
	+ GetLoadDispl()
	+ GetLoadForce()
	+ GetLocalAxes()
	+ GetMass()
	+ GetNameFromLabel()
	+ GetNameList()
	+ GetNameListOnStory()
	+ GetPanelZone()
	+ GetRestraint()
	+ GetSelected()
	+ GetSpecialPoint()
	+ GetSpring()
	+ GetSpringAssignment()
	+ GetSpringCoupled()
	+ GetTransformationMatrix()
	+ IsSpringCoupled()
	+ SetDiaphragm()
	+ SetGroupAssign()
	+ SetGUID()
	+ SetLoadDispl()
	+ SetLoadForce()
	+ SetMass()
	+ SetMassByVolume()
	+ SetMassByWeight()
	+ SetPanelZone()
	+ SetRestraint()
	+ SetSelected()
	+ SetSpecialPoint()
	+ SetSpring()
	+ SetSpringAssignment()
	+ SetSpringCoupled()
}

@enduml