@startuml
scale 2

class cPropFrame {
	+SDShape
	+ChangeName()
	+Count()
	+Delete()
	+GetAllFrameProperties()
	+GetAllFrameProperties_2()
	+GetAngle()
	+GetAutoSelectSteel()
	+GetChannel()
	+GetCircle()
	+GetConcreteL()
	+GetConcreteTee()
	+GetCoverPlatedI()
	+GetDblAngle()
	+GetDblChannel()
	+GetGeneral()
	+GetISection()
	+GetMaterial()
	+GetModifiers()
	+GetNameInPropFile()
	+GetNameList()
	+GetNonPrismatic()
	+GetPipe()
	+GetPlate()
	+GetPropFileNameList()
	+GetRebarBeam()
	+GetRebarColumn()
	+GetRebarColumn_1()
	+GetRectangle()
	+GetRod()
	+GetSDSection()
	+GetSectProps()
	+GetSteelAngle()
	+GetSteelTee()
	+GetTee()
	+GetTube()
	+GetTypeOAPI()
	+GetTypeRebar()
	+ImportProp()
	+SetAngle()
	+SetAutoSelectSteel()
	+SetChannel()
	+SetCircle()
	+SetConcreteL()
	+SetConcreteTee()
	+SetCoverPlatedI()
	+SetDblAngle()
	+SetDblChannel()
	+SetGeneral()
	+SetISection()
	+SetMaterial()
	+SetModifiers()
	+SetNonPrismatic()
	+SetPipe()
	+SetPlate()
	+SetRebarBeam()
	+SetRebarColumn()
	+SetRectangle()
	+SetRod()
	+SetSDSection()
	+SetSteelAngle()
	+SetSteelTee()
	+SetTee()
	+SetTube()
}

@enduml