@startuml
scale 2

class cPropMaterial {
	+AddMaterial()
	+ChangeName()
	+Count()
	+Delete()
	+GetDamping()
	+GetMassSource()
	+GetMassSource_1()
	+GetMaterial()
	+GetMPAnisotropic()
	+GetMPIsotropic()
	+GetMPOrthotropic()
	+GetMPUniaxial()
	+GetNameList()
	+GetOConcrete()
	+GetOConcrete_1()
	+GetONoDesign()
	+GetORebar()
	+GetORebar_1()
	+GetOSteel()
	+GetOSteel_1()
	+GetOTendon()
	+GetOTendon_1()
	+GetSSCurve()
	+GetTemp()
	+GetTypeOAPI()
	+GetWeightAndMass()
	+SetDamping()
	+SetMassSource()
	+SetMassSource_1()
	+SetMaterial()
	+SetMPAnisotropic()
	+SetMPIsotropic()
	+SetMPOrthotropic()
	+SetMPUniaxial()
	+SetOConcrete()
	+SetOConcrete_1()
	+SetONoDesign()
	+SetORebar()
	+SetORebar_1()
	+SetOSteel()
	+SetOSteel_1()
	+SetOTendon()
	+SetOTendon_1()
	+SetSSCurve()
	+SetTemp()
	+SetWeightAndMass()
}

@enduml