' Supported Formats
' *.wsd, *.pu, *.puml, *.plantuml, *.iuml
' para poder visualiza, alt+d

@startuml
scale 2

class GetActiveObject {
    +AddRef()
    +Analyze()
    +AreaElm()
    +AreaObj()
    +BridgeAdvancedSuper()
    +BridgeDesign()
    +BridgeModeler()
    +BridgeObj()
    +CableObj()
    +ConstraintDef()
    +CoordSys()
    +DatabaseTables()
    +DesignAluminum()
    +DesignColdFormed()
    +DesignCompositeBeam()
    +DesignConcrete()
    +DesignConcreteSlab()
    +DesignResults()
    +DesignShearWall()
    +DesignSteel()
    +Detailing()
    +Diaphragm()
    +EditArea()
    +EditFrame()
    +EditGeneral()
    +EditPoint()
    +EditSolid()
    +ExternalAnalysisResults()
    +File()
    +FrameObj()
    +Func()
    +GDispl()
    +GenRefLine()
    +GetDatabaseUnits()
    +GetDatabaseUnits_2()
    +GetIDsOfNames()
    +GetKeyStringsExtendedEntityData()
    +GetKeysWithStringsExtendedEntityData()
    +GetMergeTol()
    +GetModelFilename()
    +GetModelFilepath()
    +GetModelIsLocked()
    +GetPresentCoordSystem()
    +GetPresentUnits()
    +GetPresentUnits_2()
    +GetProgramInfo()
    +GetProjectInfo()
    +GetTypeInfo()
    +GetTypeInfoCount()
    +GetUserComment()
    +GetVersion()
    +GridSys()
    +GroupDef()
    +InitializeNewModel()
    +Invoke()
    +LineElm()
    +LinkElm()
    +LinkObj()
    +LoadCases()
    +LoadPatterns()
    +NamedAssign()
    +NamedDisplay()
    +NamedSet()
    +Options()
    +PatternDef()
    +PierLabel()
    +PlaneElm()
    +PointElm()
    +PointObj()
    +PropArea()
    +PropAreaSpring()
    +PropCable()
    +PropFrame()
    +PropLineSpring()
    +PropLink()
    +PropMaterial()
    +PropPointSpring()
    +PropRebar()
    +PropSolid()
    +PropTendon()
    +QueryInterface()
    +Release()
    +RespCombo()
    +Results()
    +Scheduler()
    +SectCut()
    +SelectObj()
    +SetMergeTol()
    +SetModelIsLocked()
    +SetPresentCoordSystem()
    +SetPresentUnits()
    +SetPresentUnits_2()
    +SetProjectInfo()
    +SetStringsExtendedEntityData()
    +SetUserComment()
    +SolidElm()
    +SolidObj()
    +SourceMass()
    +SpandrelLabel()
    +Story()
    +TendonObj()
    +Tower()
    +TreeIsUpdateSuspended()
    +TreeResumeUpdateData()
    +TreeSuspendUpdateData()
    +View()
}

@enduml